import { Noto_Sans_JP } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';

import { AutoRefreshSession } from './components/AutoRefreshSession';

import type { Metadata } from 'next';

import './globals.css';

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <SessionProvider>
      <html lang="ja">
        <AutoRefreshSession />
        <body className={`${notoSansJP.className} antialiased`}>{children}</body>
      </html>
    </SessionProvider>
  );
}
